version: '3'
services:
  app:
    container_name: huntapp
    restart: always
    build: .
    ports: 
      - '3000:3000'      
  mongodb:
    image: mongo
    ports: 
      - '27017:27017'
    volumes: 
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password  
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  db-data:
    driver: local
